### ISSUE TITLE
Server Image is not working

### ISSUE THREAD

**Issue by VladRafli** [VladRafli/website_cloud_research#1]
## Detail
Ketika melakukan docker run image untuk server, Container Server berhenti bekerja dengan status exited(1) atau terdapat error

`
Log error dalam Docker

> server@1.0.0 start

> node server.js

Server is starting at 5000

/server/server.js:34

if (err) throw err;

^

Error: connect ECONNREFUSED 127.0.0.1:3306

at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1128:16)

--------------------

at Protocol._enqueue (/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)

at Protocol.handshake (/server/node_modules/mysql/lib/protocol/Protocol.js:51:23)

at Connection.connect (/server/node_modules/mysql/lib/Connection.js:116:18)

at Object.<anonymous> (/server/server.js:33:4)

at Module._compile (node:internal/modules/cjs/loader:1102:14)

at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)

at Module.load (node:internal/modules/cjs/loader:967:32)

at Function.Module._load (node:internal/modules/cjs/loader:807:14)

at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)

at node:internal/main/run_main_module:17:47 {

errno: -111,

code: 'ECONNREFUSED',

syscall: 'connect',

address: '127.0.0.1',

port: 3306,

fatal: true

}

npm ERR! code 1

npm ERR! path /server

npm ERR! command failed

npm ERR! command sh -c node server.js

npm ERR! A complete log of this run can be found in:

npm ERR! /root/.npm/_logs/2020-11-18T00_35_37_456Z-debug.log
`

## Alasan mengapa Container ini tidak berjalan

Karena dalam container ini terdapat file server.js yang membutuhkan koneksi dengan database yang dimana dalam container tersebut tidak tersedia MySQL, sehingga koneksi tidak dapat ditemukan dan server akan throw error dan berhenti

Mohon bantuannya...

Note:

Mencoba membuat issue di repo sendiri. Latihan buat issue

**Comment by VladRafli** [comment]
Perlu re-design struktur hubungan antar container dalam satu OS ini sehingga masalah yang dihadapi lebih jelas

**Comment by VladRafli** [comment]
Terselesaikan dengan membuat sebuah container sendiri yang berisi image MySQL
